### ISSUE TITLE
Error while using the sxtools addon

### ISSUE THREAD

**Issue by HarshEcka** [FrandSX/sxtools-blender#1]
I used the Old version of addon or the stable release (version 3.0) and it installed perfectly and i was to setup the object and finally was able to apply the colors also. However the new beta version installs successfully but the addons fails to setup the object. I tested it both in blender 2.83 as well as in blender 2.90. Kindly look into the error.

Also the addon is really awesome and can become very handy while texturing skin (Almost like substance painter).In future support for alpha maps for pores will be very useful (Just a thought). 

Detailed video tutorial is very much needed.  Once again thanks for this wonderful addon.

**Comment by FrandSX** [comment]
Hi there! Happy to hear the addon is useful for you. Are you trying to re-setup an object that was already used with an earlier version of the addon, or is it failing with any just created mesh?

**Comment by HarshEcka** [comment]
Yes it is failing with any just created mesh.

**Comment by FrandSX** [comment]
It works normally for me, so some more info is needed.

Can you see if any error is printed on Blender's system console? In Windows, the console is opened from Window -> Toggle System Console

**Comment by HarshEcka** [comment]
Its strange today i downloaded the latest zip and it worked just fine. Yesterday i installed beta 4 release from releases page. I added suzzane and gave multires modifier and then setup the object and it worked just fine today both in simple and pbr mode. Thanks for the reply and addon.  Can you throw some light regarding handpainting skin textures (a tutorial ). There are hard to find good ones. I dont want to  do projection painting or using textures from textures.xyz. They are good but i want to do totally raw.

**Comment by FrandSX** [comment]
I've added a new beta release, since the latest zip works. Thanks for reporting this!
There have been requests for videos, they're on my to-do list :)
